services:
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - .:/var/www
    networks:
      - zen_attitude

  nginx:
    depends_on:
      - php
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
    networks:
      - zen_attitude

  db:
    image: mysql:8.0.33
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zen_attitude
      MYSQL_USER: www-data
      MYSQL_PASSWORD: secret
    networks:
      - zen_attitude

networks:
  zen_attitude: ~
