version: '3'

services:
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - .:/var/www
    networks:
      - zen-attitude

  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - zen-attitude

  db:
    image: mysql:8.0.33
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zen-attitude
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    networks:
      - zen-attitude

networks:
  zen-attitude: ~
